// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlxneitmyeyhettxlcue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhseG5laXRteWV5aGV0dHhsY3VlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NjA3NjIsImV4cCI6MjA2OTEzNjc2Mn0.5eZfR1-8G3dxE_IF5adfjhBFpbWubGOu7GjSeLyNsMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});